apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartpantry-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smartpantry-backend
  template:
    metadata:
      labels:
        app: smartpantry-backend
    spec:
      containers:
        - name: smartpantry-backend
          image: ghcr.io/adam026/smartpantry-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: MongoDbSettings__ConnectionString
              value: mongodb://mongo:27017
            - name: MongoDbSettings__DatabaseName
              value: SmartPantryDb