apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartpantry-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smartpantry-frontend
  template:
    metadata:
      labels:
        app: smartpantry-frontend
    spec:
      containers:
        - name: smartpantry-frontend
          image: ghcr.io/adam026/smartpantry-frontend:latest
          ports:
            - containerPort: 80